#ifndef EIRFRAMESOURCE_GLOBAL_H
#define EIRFRAMESOURCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EIRFRAMESOURCE_LIBRARY) || defined(VIGILLIVE_LIBRARY)
#  define EIRFRAMESOURCESHARED_EXPORT Q_DECL_EXPORT
#else
#  define EIRFRAMESOURCESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EIRFRAMESOURCE_GLOBAL_H
