#ifndef BHTTPPLUGIN_GLOBAL_H
#define BHTTPPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BHTTPPLUGIN_LIBRARY)
#  define BHTTPPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BHTTPPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BHTTPPLUGIN_GLOBAL_H
