#ifndef EIRVARIABLE_GLOBAL_H
#define EIRVARIABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EIRVARIABLE_LIBRARY)
#  define EIRVARIABLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define EIRVARIABLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EIRVARIABLE_GLOBAL_H
